//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace IVUTrafficNetworkImportService
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class NonRevenueItineraryPathKey
    {
        
        private string divisionAbbreviationField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string divisionAbbreviation
        {
            get
            {
                return this.divisionAbbreviationField;
            }
            set
            {
                this.divisionAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class NonRevenueItineraryPath
    {
        
        private NonRevenueItineraryPathKey nonRevenueItineraryPathKeyField;
        
        private ItineraryPathStop[] nonRevenueItineraryPathField;
        
        private Validity validityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NonRevenueItineraryPathKey nonRevenueItineraryPathKey
        {
            get
            {
                return this.nonRevenueItineraryPathKeyField;
            }
            set
            {
                this.nonRevenueItineraryPathKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itineraryPathStop", IsNullable=false)]
        public ItineraryPathStop[] nonRevenueItineraryPath
        {
            get
            {
                return this.nonRevenueItineraryPathField;
            }
            set
            {
                this.nonRevenueItineraryPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Validity validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class ItineraryPathStop
    {
        
        private NetworkPointKey networkPointKeyField;
        
        private ItineraryPathLeg itineraryPathLegField;
        
        private DurationAssignment[] stopDurationAssignmentsField;
        
        private DurationAssignment[] waitDurationAssignmentsField;
        
        private bool passThroughField;
        
        private bool passThroughFieldSpecified;
        
        private bool requestStopField;
        
        private bool requestStopFieldSpecified;
        
        private bool noBoardingField;
        
        private bool noBoardingFieldSpecified;
        
        private bool noAlightingField;
        
        private bool noAlightingFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NetworkPointKey networkPointKey
        {
            get
            {
                return this.networkPointKeyField;
            }
            set
            {
                this.networkPointKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ItineraryPathLeg itineraryPathLeg
        {
            get
            {
                return this.itineraryPathLegField;
            }
            set
            {
                this.itineraryPathLegField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("stopDurationAssignment", IsNullable=false)]
        public DurationAssignment[] stopDurationAssignments
        {
            get
            {
                return this.stopDurationAssignmentsField;
            }
            set
            {
                this.stopDurationAssignmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("waitDurationAssignment", IsNullable=false)]
        public DurationAssignment[] waitDurationAssignments
        {
            get
            {
                return this.waitDurationAssignmentsField;
            }
            set
            {
                this.waitDurationAssignmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool passThrough
        {
            get
            {
                return this.passThroughField;
            }
            set
            {
                this.passThroughField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool passThroughSpecified
        {
            get
            {
                return this.passThroughFieldSpecified;
            }
            set
            {
                this.passThroughFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool requestStop
        {
            get
            {
                return this.requestStopField;
            }
            set
            {
                this.requestStopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestStopSpecified
        {
            get
            {
                return this.requestStopFieldSpecified;
            }
            set
            {
                this.requestStopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool noBoarding
        {
            get
            {
                return this.noBoardingField;
            }
            set
            {
                this.noBoardingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool noBoardingSpecified
        {
            get
            {
                return this.noBoardingFieldSpecified;
            }
            set
            {
                this.noBoardingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool noAlighting
        {
            get
            {
                return this.noAlightingField;
            }
            set
            {
                this.noAlightingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool noAlightingSpecified
        {
            get
            {
                return this.noAlightingFieldSpecified;
            }
            set
            {
                this.noAlightingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class NetworkPointKey
    {
        
        private string abbreviationField;
        
        private string externalNumberField;
        
        private string[] typeField;
        
        private string divisionAbbreviationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string externalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("type", Order=2)]
        public string[] type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string divisionAbbreviation
        {
            get
            {
                return this.divisionAbbreviationField;
            }
            set
            {
                this.divisionAbbreviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class ItineraryPathLeg
    {
        
        private string linkDescriptionField;
        
        private DurationAssignment[] runDurationAssignmentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string linkDescription
        {
            get
            {
                return this.linkDescriptionField;
            }
            set
            {
                this.linkDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("runDurationAssignment", IsNullable=false)]
        public DurationAssignment[] runDurationAssignments
        {
            get
            {
                return this.runDurationAssignmentsField;
            }
            set
            {
                this.runDurationAssignmentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class DurationAssignment
    {
        
        private string timeField;
        
        private string profileAbbreviationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="duration", Order=0)]
        public string time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string profileAbbreviation
        {
            get
            {
                return this.profileAbbreviationField;
            }
            set
            {
                this.profileAbbreviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class Validity
    {
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        private bool toDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toDateSpecified
        {
            get
            {
                return this.toDateFieldSpecified;
            }
            set
            {
                this.toDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class RoutePatternKey
    {
        
        private string descriptionField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class RoutePattern
    {
        
        private RoutePatternKey routePatternKeyField;
        
        private string abbreviationField;
        
        private string descriptionField;
        
        private Validity validityField;
        
        private ItineraryPathStop[] routePatternItineraryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RoutePatternKey routePatternKey
        {
            get
            {
                return this.routePatternKeyField;
            }
            set
            {
                this.routePatternKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Validity validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itineraryPathStop", IsNullable=false)]
        public ItineraryPathStop[] routePatternItinerary
        {
            get
            {
                return this.routePatternItineraryField;
            }
            set
            {
                this.routePatternItineraryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class DepotKey
    {
        
        private string abbreviationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class RouteKey
    {
        
        private string abbreviationField;
        
        private string divisionAbbreviationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string divisionAbbreviation
        {
            get
            {
                return this.divisionAbbreviationField;
            }
            set
            {
                this.divisionAbbreviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class Route
    {
        
        private RouteKey routeKeyField;
        
        private string abbreviationField;
        
        private string descriptionField;
        
        private string avlNumberField;
        
        private DepotKey[] depotsField;
        
        private Validity validityField;
        
        private RoutePattern[] routePatternsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RouteKey routeKey
        {
            get
            {
                return this.routeKeyField;
            }
            set
            {
                this.routeKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=3)]
        public string avlNumber
        {
            get
            {
                return this.avlNumberField;
            }
            set
            {
                this.avlNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("depot")]
        public DepotKey[] depots
        {
            get
            {
                return this.depotsField;
            }
            set
            {
                this.depotsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Validity validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("routePattern")]
        public RoutePattern[] routePatterns
        {
            get
            {
                return this.routePatternsField;
            }
            set
            {
                this.routePatternsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class LinkKey
    {
        
        private NetworkPointKey fromNetworkPointKeyField;
        
        private NetworkPointKey toNetworkPointKeyField;
        
        private string descriptionField;
        
        private string divisionAbbreviationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NetworkPointKey fromNetworkPointKey
        {
            get
            {
                return this.fromNetworkPointKeyField;
            }
            set
            {
                this.fromNetworkPointKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public NetworkPointKey toNetworkPointKey
        {
            get
            {
                return this.toNetworkPointKeyField;
            }
            set
            {
                this.toNetworkPointKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string divisionAbbreviation
        {
            get
            {
                return this.divisionAbbreviationField;
            }
            set
            {
                this.divisionAbbreviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class Link
    {
        
        private LinkKey linkKeyField;
        
        private string divisionAbbreviationField;
        
        private string descriptionField;
        
        private string distanceField;
        
        private Validity validityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public LinkKey linkKey
        {
            get
            {
                return this.linkKeyField;
            }
            set
            {
                this.linkKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string divisionAbbreviation
        {
            get
            {
                return this.divisionAbbreviationField;
            }
            set
            {
                this.divisionAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=3)]
        public string distance
        {
            get
            {
                return this.distanceField;
            }
            set
            {
                this.distanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Validity validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class AddressKey
    {
        
        private string abbreviationField;
        
        private string externalNumberField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string externalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class Coordinate
    {
        
        private string xField;
        
        private string yField;
        
        private string zField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class NetworkPoint
    {
        
        private NetworkPointKey networkPointKeyField;
        
        private string divisionAbbreviationField;
        
        private NetworkPointAreaKey[] networkPointAreaKeyField;
        
        private string abbreviationField;
        
        private string descriptionField;
        
        private string externalNumberField;
        
        private Coordinate coordinateField;
        
        private AddressKey ownerField;
        
        private string stoptypeField;
        
        private Validity validityField;
        
        private bool isReliefPointField;
        
        private bool isReliefPointFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NetworkPointKey networkPointKey
        {
            get
            {
                return this.networkPointKeyField;
            }
            set
            {
                this.networkPointKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string divisionAbbreviation
        {
            get
            {
                return this.divisionAbbreviationField;
            }
            set
            {
                this.divisionAbbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("networkPointAreaKey", IsNullable=true, Order=2)]
        public NetworkPointAreaKey[] networkPointAreaKey
        {
            get
            {
                return this.networkPointAreaKeyField;
            }
            set
            {
                this.networkPointAreaKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string externalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Coordinate coordinate
        {
            get
            {
                return this.coordinateField;
            }
            set
            {
                this.coordinateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public AddressKey owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string stoptype
        {
            get
            {
                return this.stoptypeField;
            }
            set
            {
                this.stoptypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public Validity validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool isReliefPoint
        {
            get
            {
                return this.isReliefPointField;
            }
            set
            {
                this.isReliefPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isReliefPointSpecified
        {
            get
            {
                return this.isReliefPointFieldSpecified;
            }
            set
            {
                this.isReliefPointFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class NetworkPointAreaKey
    {
        
        private string abbreviationField;
        
        private string externalNumberField;
        
        private string typeField;
        
        private string divisionAbbreviationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string abbreviation
        {
            get
            {
                return this.abbreviationField;
            }
            set
            {
                this.abbreviationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string externalNumber
        {
            get
            {
                return this.externalNumberField;
            }
            set
            {
                this.externalNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string divisionAbbreviation
        {
            get
            {
                return this.divisionAbbreviationField;
            }
            set
            {
                this.divisionAbbreviationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class NetworkPointArea
    {
        
        private NetworkPointAreaKey networkPointAreaKeyField;
        
        private string descriptionField;
        
        private Validity validityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public NetworkPointAreaKey networkPointAreaKey
        {
            get
            {
                return this.networkPointAreaKeyField;
            }
            set
            {
                this.networkPointAreaKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Validity validity
        {
            get
            {
                return this.validityField;
            }
            set
            {
                this.validityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class trafficNetwork
    {
        
        private NetworkPointArea[] networkPointAreasField;
        
        private NetworkPoint[] networkPointsField;
        
        private Link[] linksField;
        
        private Route[] routesField;
        
        private NonRevenueItineraryPath[] nonRevenueItineraryPathsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("networkPointArea")]
        public NetworkPointArea[] networkPointAreas
        {
            get
            {
                return this.networkPointAreasField;
            }
            set
            {
                this.networkPointAreasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("networkPoint")]
        public NetworkPoint[] networkPoints
        {
            get
            {
                return this.networkPointsField;
            }
            set
            {
                this.networkPointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("link")]
        public Link[] links
        {
            get
            {
                return this.linksField;
            }
            set
            {
                this.linksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("route")]
        public Route[] routes
        {
            get
            {
                return this.routesField;
            }
            set
            {
                this.routesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("nonRevenueItineraryPath")]
        public NonRevenueItineraryPath[] nonRevenueItineraryPaths
        {
            get
            {
                return this.nonRevenueItineraryPathsField;
            }
            set
            {
                this.nonRevenueItineraryPathsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote", ConfigurationName="IVUTrafficNetworkImportService.StandardTrafficNetworkImportWebFacade")]
    public interface StandardTrafficNetworkImportWebFacade
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://intf.mb.ivu.de/network/standardimport/remote", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(object), Action="http://intf.mb.ivu.de/network/standardimport/remote", Name="TechnicalFaultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<IVUTrafficNetworkImportService.importTrafficNetworkResponse> importTrafficNetworkAsync(IVUTrafficNetworkImportService.importTrafficNetwork request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class TrafficNetworkImportRequest
    {
        
        private string profileNameField;
        
        private trafficNetwork trafficNetworkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string profileName
        {
            get
            {
                return this.profileNameField;
            }
            set
            {
                this.profileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public trafficNetwork trafficNetwork
        {
            get
            {
                return this.trafficNetworkField;
            }
            set
            {
                this.trafficNetworkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class TrafficNetworkImportResponse
    {
        
        private string protocolTransactionIdField;
        
        private TrafficNetworkImportResponseProtocolEntry[] protocolEntryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string protocolTransactionId
        {
            get
            {
                return this.protocolTransactionIdField;
            }
            set
            {
                this.protocolTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocolEntry", IsNullable=true, Order=1)]
        public TrafficNetworkImportResponseProtocolEntry[] protocolEntry
        {
            get
            {
                return this.protocolEntryField;
            }
            set
            {
                this.protocolEntryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public partial class TrafficNetworkImportResponseProtocolEntry
    {
        
        private ProtocolEntryType typeField;
        
        private string codeField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProtocolEntryType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote")]
    public enum ProtocolEntryType
    {
        
        /// <remarks/>
        INFORMATION,
        
        /// <remarks/>
        WARNING,
        
        /// <remarks/>
        ERROR,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importTrafficNetwork
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote", Order=0)]
        public IVUTrafficNetworkImportService.TrafficNetworkImportRequest TrafficNetworkImportRequest;
        
        public importTrafficNetwork()
        {
        }
        
        public importTrafficNetwork(IVUTrafficNetworkImportService.TrafficNetworkImportRequest TrafficNetworkImportRequest)
        {
            this.TrafficNetworkImportRequest = TrafficNetworkImportRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class importTrafficNetworkResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.mb.ivu.de/network/standardimport/remote", Order=0)]
        public IVUTrafficNetworkImportService.TrafficNetworkImportResponse TrafficNetworkImportResponse;
        
        public importTrafficNetworkResponse()
        {
        }
        
        public importTrafficNetworkResponse(IVUTrafficNetworkImportService.TrafficNetworkImportResponse TrafficNetworkImportResponse)
        {
            this.TrafficNetworkImportResponse = TrafficNetworkImportResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface StandardTrafficNetworkImportWebFacadeChannel : IVUTrafficNetworkImportService.StandardTrafficNetworkImportWebFacade, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class StandardTrafficNetworkImportWebFacadeClient : System.ServiceModel.ClientBase<IVUTrafficNetworkImportService.StandardTrafficNetworkImportWebFacade>, IVUTrafficNetworkImportService.StandardTrafficNetworkImportWebFacade
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StandardTrafficNetworkImportWebFacadeClient() : 
            base(StandardTrafficNetworkImportWebFacadeClient.GetDefaultBinding(), StandardTrafficNetworkImportWebFacadeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.StandardTrafficNetworkImportWebFacadeBeanPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StandardTrafficNetworkImportWebFacadeClient(EndpointConfiguration endpointConfiguration) : 
                base(StandardTrafficNetworkImportWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), StandardTrafficNetworkImportWebFacadeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StandardTrafficNetworkImportWebFacadeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StandardTrafficNetworkImportWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StandardTrafficNetworkImportWebFacadeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StandardTrafficNetworkImportWebFacadeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StandardTrafficNetworkImportWebFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IVUTrafficNetworkImportService.importTrafficNetworkResponse> IVUTrafficNetworkImportService.StandardTrafficNetworkImportWebFacade.importTrafficNetworkAsync(IVUTrafficNetworkImportService.importTrafficNetwork request)
        {
            return base.Channel.importTrafficNetworkAsync(request);
        }
        
        public System.Threading.Tasks.Task<IVUTrafficNetworkImportService.importTrafficNetworkResponse> importTrafficNetworkAsync(IVUTrafficNetworkImportService.TrafficNetworkImportRequest TrafficNetworkImportRequest)
        {
            IVUTrafficNetworkImportService.importTrafficNetwork inValue = new IVUTrafficNetworkImportService.importTrafficNetwork();
            inValue.TrafficNetworkImportRequest = TrafficNetworkImportRequest;
            return ((IVUTrafficNetworkImportService.StandardTrafficNetworkImportWebFacade)(this)).importTrafficNetworkAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.StandardTrafficNetworkImportWebFacadeBeanPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.StandardTrafficNetworkImportWebFacadeBeanPort))
            {
                return new System.ServiceModel.EndpointAddress("http://bpsp29app02-1.ivu-ag.com:15020/intf.trafficnetwork.standardimport.impl/Sta" +
                        "ndardTrafficNetworkImportWebFacadeBean");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return StandardTrafficNetworkImportWebFacadeClient.GetBindingForEndpoint(EndpointConfiguration.StandardTrafficNetworkImportWebFacadeBeanPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return StandardTrafficNetworkImportWebFacadeClient.GetEndpointAddress(EndpointConfiguration.StandardTrafficNetworkImportWebFacadeBeanPort);
        }
        
        public enum EndpointConfiguration
        {
            
            StandardTrafficNetworkImportWebFacadeBeanPort,
        }
    }
}
